### ISSUE TITLE
Latest gcc

### ISSUE THREAD

**Issue by MartinXPN** [MartinXPN/LambdaJudge#25]
Only c++17 is supported with the current gcc version. We can add the support for the latest gcc with c++20 and c++23 (beta) support.
One way is to use homebrew for linux: https://docs.brew.sh/Homebrew-on-Linux
And then install the gcc formulate: https://formulae.brew.sh/formula/gcc

This might come with too many dependencies, so might need to be careful.

**Comment by edogrigqv2** [comment]
I think the support for C++20 will be added to yum sooner or later. Better to wait.

**Comment by MartinXPN** [comment]
The latest Amazon 2023 images support GCC 11 which supports C++20
