### ISSUE TITLE
Have functions with predefined templates to get input and return output

### ISSUE THREAD

**Issue by MartinXPN** [MartinXPN/LambdaJudge#31]
Maybe use something like: https://github.com/OpenAPITools/openapi-generator

to get input in several languages and return the output as a function instead of reading input/output from stdin/stdout.

**Comment by edogrigqv2** [comment]
OpenAPI is overkill and very complicated.
It was decided to have an IO utility template offered in the beginning of the code to help with IO in languages like JS.
@MartinXPN Let's close this issue and open a new one.

**Comment by MartinXPN** [comment]
I agree, let's move this to a new one
