### ISSUE TITLE
Slow running submissions

### ISSUE THREAD

**Issue by davitmarg** [MartinXPN/LambdaJudge#86]
Some submissions especially the ones written on python run really slow causing TLE verdicts.

Here is a list of problematic problems
https://profound.academy/algorithms-data-structures/tFBQluErcpcsJVKmNlY5 
https://profound.academy/algorithms-data-structures/q4Iww8gYMGnA9A5kvFJF
https://profound.academy/algorithms-data-structures/ZIIhwXEVAMaLm7eiqSxW
https://profound.academy/algorithms-data-structures/cFjSI2aHirokToLfM5cm

**Comment by MartinXPN** [comment]
Resolved with the recent changes
